version: '3'

services:
    mongodb1:
        image: mongo:latest
        restart: always
        container_name: mongodb1
        volumes:
        - ./users.js:/docker-entrypoint-initdb.d/001_users.js:ro
        - mongodata1:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
        environment:
            - MONGO_INITDB_DATABASE=clube-prod
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=proj2501
        networks:
            - captain-overlay-network

    mongodb2:
        image: mongo:latest
        restart: always
        container_name: mongodb2
        volumes:
        - ./users.js:/docker-entrypoint-initdb.d/001_users.js:ro
        - mongodata2:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
        environment:
            - MONGO_INITDB_DATABASE=clube-prod
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=proj2501
        networks:
            - captain-overlay-network
      
    mongodb3:
        image: mongo:latest
        restart: always
        container_name: mongodb3
        volumes:
        - ./users.js:/docker-entrypoint-initdb.d/001_users.js:ro
        - mongodata3:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1" ]
        environment:
            - MONGO_INITDB_DATABASE=clube-prod
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=proj2501
        networks:
            - captain-overlay-network
    
    mongosetup:
        image: "mongo-setup"
        build: "./mongo-setup"
        container_name: "mongosetup"
        depends_on:
            - mongodb1
        volumes:
            - mongostatus:/data/
        networks:
            - captain-overlay-network
    

volumes:
    mongodata1:
    mongodata2:
    mongodata3:
    mongostatus:

networks:
  captain-overlay-network:
    external: true